version: "3"

services:
    mssql:
        image: mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
        environment:
            'ACCEPT_EULA':  'y'
            'SA_PASSWORD': 'magic11!'
        ports: 
            - 1433:1433

    mssql-test:
        image: mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
        environment:
            'ACCEPT_EULA':  'y'
            'SA_PASSWORD': 'magic11!'
        ports: 
            - 1434:1433

