spring:
    datasource:
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        url: jdbc:sqlserver://localhost;database=master
        username: sa
        password: magic11!
    jpa:
        show-sql: false
        hibernate:
            format_sql: false
            dialect: org.hibernate.dialect.SQLServer2012Dialect
            ddl-auto: validate
    flyway:
        url: jdbc:sqlserver://localhost;database=master
        schemas: dbo
        user: sa
        password: magic11!
        baseline-on-migrate: true

