spring:
    data:
        web:
            pageable:
                default-page-size: 100
    datasource:
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        url: jdbc:sqlserver://localhost;database=master
        username: sa
        password: magic11!
    jpa:
        show-sql: false
        hibernate:
            format_sql: false
            dialect: org.hibernate.dialect.SQLServer2012Dialect
            ddl-auto: validate
        properties:
            hibernate:
                generate_statistics: true
                jdbc:
                    batch_size: 50
                order_inserts: true
                order_updates: true
    flyway:
        url: jdbc:sqlserver://localhost;database=master
        schemas: dbo
        user: sa
        password: magic11!
        baseline-on-migrate: true
